[package]
name = "pciutils-sys"
version = "0.1.0"
edition = "2021"
authors = ["CordlessCoder"]
readme = "README.md"
description = "Raw bindings to pciutils"

[dependencies]

[build-dependencies]
bindgen = "0.66.1"
